[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "owl-imdl"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = [

]
authors = [
  { name = "aikwen", email = "kwen.zou@outlook.com" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
]

dependencies = []

[project.urls]
Documentation = "https://github.com/aikwen/owl#readme"
Issues = "https://github.com/aikwen/owl/issues"
Source = "https://github.com/aikwen/owl"

[tool.hatch.version]
path = "src/owl/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/owl tests}"

[tool.coverage.run]
source_pkgs = ["owl", "tests"]
branch = true
parallel = true
omit = [
  "src/owl/__about__.py",
]

[tool.coverage.paths]
owl = ["src/owl", "*/owl/src/owl"]
tests = ["tests", "*/owl/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
[tool.hatch.build.targets.wheel]
packages = ["src/owl"]
