"""Visualizer protocol definitions.

This module defines the protocol used by inference runtimes to generate and
save visualization images from parsed model outputs.
"""

from pathlib import Path
from typing import Protocol, TypeAlias

from torch import Tensor

from ..outputs.types import ParsedTensorOutputs, TensorOutputValue


VisualizationOutputs: TypeAlias = dict[str, TensorOutputValue]
"""Named visualization image batches returned by a visualizer.

Each dictionary key defines a base output marker used by the inference runtime
when constructing file names. Each value may contain either:

- one batched image tensor with shape ``[B, C, H, W]``; or
- a non-empty ordered list or tuple of batched image tensors with that shape.

A single tensor keeps its base output marker unchanged. A list or tuple is
expanded by the inference runtime using one-based numeric suffixes while
preserving the original tensor order.

For example, the output::

    {
        "prediction": Tensor[B, C, H, W],
        "edge": [
            Tensor[B, C, H, W],
            Tensor[B, C, H, W],
            Tensor[B, C, H, W],
        ],
    }

is expanded into the following output markers::

    prediction
    edge_1
    edge_2
    edge_3

For a sample whose TP name is ``Tp_D_NRN_001``, the runtime constructs file
names such as::

    Tp_D_NRN_001_prediction.png
    Tp_D_NRN_001_edge_1.png
    Tp_D_NRN_001_edge_2.png
    Tp_D_NRN_001_edge_3.png
"""


class Visualizer(Protocol):
    """Protocol implemented by inference visualizers.

    Visualization is performed in two stages.

    First, the model exposes tensors through ``visual:*`` output keys. The
    model output parser removes the ``visual:`` prefix and passes the resulting
    ``ParsedTensorOutputs`` mapping to ``visualize``.

    For example, the raw model output::

        {
            "visual:prediction": prediction,
            "visual:edges": [edge_1, edge_2, edge_3],
        }

    is parsed into::

        {
            "prediction": prediction,
            "edges": [edge_1, edge_2, edge_3],
        }

    The visualizer then converts these model-provided tensors into final image
    tensors suitable for saving. It returns a ``VisualizationOutputs`` mapping
    whose keys describe the generated image types.

    The input and output mappings have different responsibilities:

    - ``visual_outputs`` contains model-provided visualization materials;
    - ``VisualizationOutputs`` contains final image tensors generated by the
      visualizer.

    The visualizer may preserve the input names, rename them, combine several
    model outputs into one image, or produce additional derived images such as
    overlays and comparisons.

    After ``visualize`` returns, the inference runtime:

    1. expands list and tuple values using one-based numeric suffixes;
    2. validates every batched image tensor;
    3. pairs each image with the matching ``tp_name``;
    4. constructs an owl-managed destination path; and
    5. invokes ``save`` once for every individual image.

    Example:
        Define a visualizer that produces a prediction, three progressive edge
        outputs, and a derived overlay:

        >>> class ProgressiveVisualizer:
        ...     def visualize(
        ...         self,
        ...         *,
        ...         visual_outputs: ParsedTensorOutputs,
        ...     ) -> VisualizationOutputs:
        ...         prediction = visual_outputs["prediction"]
        ...         edges = visual_outputs["edges"]
        ...         overlay = build_overlay(
        ...             prediction=prediction,
        ...             edges=edges,
        ...         )
        ...
        ...         return {
        ...             "prediction": prediction,
        ...             "edge": edges,
        ...             "overlay": overlay,
        ...         }
        ...
        ...     def save(
        ...         self,
        ...         *,
        ...         image: Tensor,
        ...         path: Path,
        ...     ) -> None:
        ...         save_tensor_image(image, path)

        If ``edges`` contains three tensors, the runtime expands the returned
        mapping into the following output markers:

        >>> output_markers = [
        ...     "prediction",
        ...     "edge_1",
        ...     "edge_2",
        ...     "edge_3",
        ...     "overlay",
        ... ]

        For a TP named ``Tp_D_NRN_001``, the corresponding files are named:

        >>> output_paths = [
        ...     "Tp_D_NRN_001_prediction.png",
        ...     "Tp_D_NRN_001_edge_1.png",
        ...     "Tp_D_NRN_001_edge_2.png",
        ...     "Tp_D_NRN_001_edge_3.png",
        ...     "Tp_D_NRN_001_overlay.png",
        ... ]

    Notes:
        The runtime guarantees that ``visual_outputs`` contains at least one
        parsed ``visual:*`` model output before invoking ``visualize``.

        ``visualize`` must return at least one named visualization output.

        Every output key is treated as a base file-name marker. It must be a
        non-empty string that does not contain path components. Examples of
        valid names include ``prediction``, ``edge``, ``overlay``, and
        ``comparison``.

        A single tensor value produces one output marker without a numeric
        suffix. For example::

            {
                "prediction": prediction,
            }

        produces ``<tp_name>_prediction.png``.

        A list or tuple value represents an ordered collection of related
        visualization outputs. The runtime preserves its order and appends
        one-based numeric suffixes. For example::

            {
                "edge": [edge_1, edge_2, edge_3],
            }

        produces ``<tp_name>_edge_1.png``,
        ``<tp_name>_edge_2.png``, and
        ``<tp_name>_edge_3.png``.

        Lists and tuples must not be empty. Every element must be a batched
        image tensor.

        Every returned tensor must have shape ``[B, C, H, W]``. Its leading
        dimension must match the number of ``tp_name`` values in the
        corresponding dataset batch. The tensor at batch index ``i`` must
        represent the same sample as ``tp_name[i]``.

        Owl does not prescribe a specific channel count, dtype, or numeric
        range for visualization tensors. The visualizer implementation and its
        ``save`` method must agree on how each tensor is interpreted and
        encoded.

        ``save`` receives one image at a time after the runtime removes the
        batch dimension. The image therefore has shape ``[C, H, W]``. The
        runtime detaches the tensor, moves it to the CPU, and supplies the
        complete destination path.

        Implementations may choose any appropriate image-writing backend, but
        they must write the image to the supplied path rather than replacing
        the runtime-managed destination.
    """

    def visualize(
        self,
        *,
        visual_outputs: ParsedTensorOutputs,
    ) -> VisualizationOutputs:
        """Generate named visualization image batches.

        Args:
            visual_outputs:
                Model-provided tensor payloads parsed from ``visual:*`` output
                keys.

                Each value may be a single tensor or an ordered list or tuple
                of tensors. The visualizer is responsible for interpreting
                these tensors and converting them into final visualization
                images.

        Returns:
            Mapping from base output markers to final visualization image
            payloads.

            A value may be one batched image tensor or a non-empty ordered list
            or tuple of batched image tensors. Every tensor must have shape
            ``[B, C, H, W]`` and correspond to the input samples at the same
            batch indices.

            Single tensors retain their output marker. Lists and tuples are
            expanded by the runtime using one-based suffixes such as
            ``edge_1``, ``edge_2``, and ``edge_3``.
        """
        ...

    def save(
        self,
        *,
        image: Tensor,
        path: Path,
    ) -> None:
        """Save one visualization image to the supplied destination.

        Args:
            image:
                One final visualization image tensor with shape
                ``[C, H, W]``.

                The runtime detaches this tensor and moves it to the CPU before
                invoking ``save``.
            path:
                Complete destination path generated and managed by the
                inference runtime.

                The file name combines the TP name with the expanded
                visualization output marker, for example
                ``Tp_D_NRN_001_edge_2.png``.
        """
        ...
